kind: pipeline
type: docker
name: default

steps:
- name: build
  image: arminfriedl/xwim-build
  commands:
    - meson wrap install gtest
    - meson build
    - ninja -C build
    - ninja -C build test && ninja -C build coverage
    - echo "******** TEST LOGS ***********"
    - cat build/meson-logs/testlog.txt
    - echo "****** COVERAGE LOGS *********"
    - cat build/meson-logs/coverage.txt

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: docker
name: release

steps:
- name: build
  image: arminfriedl/xwim-build
  commands:
    - meson wrap install gtest
    - meson --buildtype=release build
    - ninja -C build
    - mkdir xwim-${DRONE_TAG}-x86_64-glibc-linux
    - mv build/src/xwim xwim-${DRONE_TAG}-x86_64-glibc-linux

- name: package
  image: arminfriedl/xwim-build
  commands:
    - tar cjf xwim-${DRONE_TAG}-x86_64-glibc-linux.tar.bz2 xwim-${DRONE_TAG}-x86_64-glibc-linux/xwim
    - tar czf xwim-${DRONE_TAG}-x86_64-glibc-linux.tar.gz xwim-${DRONE_TAG}-x86_64-glibc-linux/xwim
    - zip -r xwim-${DRONE_TAG}-x86_64-glibc-linux.zip xwim-${DRONE_TAG}-x86_64-glibc-linux

- name: publish
  image: plugins/gitea-release
  settings:
    base_url: https://git.friedl.net
    api_key:
      from_secret: gitea_token
    files:
      - xwim-${DRONE_TAG}-x86_64-glibc-linux.tar.bz2
      - xwim-${DRONE_TAG}-x86_64-glibc-linux.tar.gz
      - xwim-${DRONE_TAG}-x86_64-glibc-linux.zip
    title: xwim ${DRONE_TAG}
    checksum:
      - md5
      - sha256

trigger:
  event:
  - tag
