kind: pipeline
type: docker
name: default

steps:
- name: build
  image: arminfriedl/xwim-build
  commands:
    - meson build
    - ninja -C build

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: docker
name: release

steps:
- name: build
  image: arminfriedl/xwim-build
  commands:
    - meson --buildtype release build
    - ninja -C build
    - mkdir xwim-${DRONE_TAG}-x86_64-linux
    - mv build/src/xwim xwim-${DRONE_TAG}-x86_64-linux

- name: package
  image: arminfriedl/xwim-build
  commands:
    - tar cjf xwim-${DRONE_TAG}-x86_64-linux.tar.bz2 xwim-${DRONE_TAG}-x86_64-linux/xwim
    - tar czf xwim-${DRONE_TAG}-x86_64-linux.tar.gz xwim-${DRONE_TAG}-x86_64-linux/xwim

- name: publish
  image: plugins/gitea-release
  settings:
    base_url: https://git.friedl.net
    api_key:
      from_secret: gitea_token
    files:
      - xwim-${DRONE_TAG}-x86_64-linux.tar.bz2
      - xwim-${DRONE_TAG}-x86_64-linux.tar.gz
    title: xwim ${DRONE_TAG}
    note: CHANGELOG.md
    checksum:
      - md5
      - sha256

trigger:
  event:
  - tag
