kind: pipeline
type: docker
name: default

steps:
- name: build-shared
  image: arminfriedl/xwim-build:shared
  commands:
    - meson target/shared
    - ninja -C target/shared
    - mv target/shared/src/xwim xwim-x86_64-glibc-linux-shared

- name: build-static
  image: arminfriedl/xwim-build:static
  commands:
    - meson --default-library=static target/static
    - ninja -C target/static
    - mv target/static/src/xwim xwim-x86_64-musl-linux-static

- name: publish-binaries
  image: appleboy/drone-scp
  settings:
    host: friedl.net
    username:
      from_secret: deploy_user
    password:
      from_secret: deploy_password
    port: 22
    target: /var/services/dirlist/repo/cicd/xwim/${DRONE_COMMIT_SHA:0:8}/
    source:
      - xwim-x86_64-glibc-linux-shared
      - xwim-x86_64-musl-linux-static
  depends_on:
    - build-shared
    - build-static

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: docker
name: release

steps:
- name: build-shared
  image: arminfriedl/xwim-build:shared
  commands:
    - meson --buildtype=release target/shared
    - ninja -C target/shared
    - strip target/shared/src/xwim
    - mkdir xwim-${DRONE_TAG}-x86_64-glibc-linux-shared
    - mv target/shared/src/xwim xwim-${DRONE_TAG}-x86_64-glibc-linux-shared

- name: build-static
  image: arminfriedl/xwim-build:static
  commands:
    - meson --buildtype=release --default-library=static target/static
    - ninja -C target/static
    - strip target/static/src/xwim
    - mkdir xwim-${DRONE_TAG}-x86_64-musl-linux-static
    - mv target/static/src/xwim xwim-${DRONE_TAG}-x86_64-musl-linux-static

- name: package
  image: arminfriedl/xwim-build
  commands:
    - tar czf xwim-${DRONE_TAG}-x86_64-glibc-linux-shared.tar.gz xwim-${DRONE_TAG}-x86_64-glibc-linux-shared/xwim
    - tar czf xwim-${DRONE_TAG}-x86_64-musl-linux-static.tar.gz xwim-${DRONE_TAG}-x86_64-musl-linux-static/xwim
  depends_on:
    - build-shared
    - build-static

- name: publish
  image: plugins/gitea-release
  settings:
    base_url: https://git.friedl.net
    api_key:
      from_secret: gitea_token
    files:
      - xwim-${DRONE_TAG}-x86_64-glibc-linux-shared.tar.gz
      - xwim-${DRONE_TAG}-x86_64-musl-linux-static.tar.gz
    title: xwim ${DRONE_TAG}
    checksum:
      - md5
      - sha256
  depends_on:
    - package

trigger:
  event:
  - tag
